# base image
# FROM nvcr.io/nvidia/pytorch:22.02-py3 as base
FROM nvcr.io/nvidia/pytorch:23.05-py3 as base
# FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel as base
# FROM nvcr.io/nvidia/pytorch:21.06-py3 as base

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
#     && find /etc/apt/sources.list /etc/apt/sources.list.d/ -type f -exec sed -Ei 's!http://!'http://devops.io:3142'/!g' {} \; \
#     && find /etc/apt/sources.list /etc/apt/sources.list.d/ -type f -exec sed -Ei 's!https://!'http://devops.io:3142'/HTTPS///!g' {} \;


# RUN echo "Acquire::http::Proxy \"http://devops.io:3142\";" > /etc/apt/apt.conf.d/00aptproxy
RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
RUN sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y git ninja-build libglib2.0-0 libsm6 libxrender-dev \
        libxext6 libgl1-mesa-glx sudo openssh-server ffmpeg tmux htop zip unzip\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# RUN conda clean --all
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple

# RUN pip install torch==2.0.0+cpu torchvision==0.15.1+cpu -f https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html  -i https://mirror.baidu.com/pypi/simple 
# 换中科大源
# RUN pip config set global.index-url https://pypi.mirrors.ustc.edu.cn/simple

# RUN pip install omegaconf fvcore iopath submitit opencv-python==4.5.5.64 Pillow==9.5.0 gradio==3.43.2 xformers==0.0.18 faiss-cpu onnxruntime-gpu==1.15.1 -i https://pypi.mirrors.ustc.edu.cn/simple

# Development image
FROM base as development

ARG USERNAME=myuser
ARG USER_UID
ARG USER_GID=${USER_UID}

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && chmod -R 777 /home/$USERNAME

# Switch to the new user
USER $USERNAME
WORKDIR /home/$USERNAME


